### ISSUE TITLE
Specify contract address in environment variable

### ISSUE THREAD

**Issue by leovct** [Everest-Option-Exchange-Team/test-interface#7]
## Motivation
At the moment, the contract address is specified in `src/App.js` like this:
`const contractAddress = "0x5081f431918Ccc62DBDfaCBc11f34B4166A27450";`

Each time we deploy a new contract, we need to update this file and create a new commit/PR.

That's why we should set this value in an environment variable (in `.env` locally and in github env variables for the CI).\
And then, we could use it like this in the code:
```js
require("dotenv").config();

const { CONTRACT_ADDRESS } = process.env;
```

## Tasks
- [x] Update `App.js` to use the environment variable value instead of a hard-coded string.
- [x] Update `.env.sample` to add `CONTRACT_ADDRESS=CHANGE_ME`.
- [x] Update `README.md` and the documentation about configuring the environment file.
